/* global describe, it, before */

require('should');

const zapier = require('zapier-platform-core');

const App = require('../index');
const appTester = zapier.createAppTester(App);

process.env.AIRSHIP_PROTOCOL = 'https'
process.env.AIRSHIP_DOMAIN = 'secure.airship.co.uk'
// process.env.AIRSHIP_PROTOCOL = 'http'
// process.env.AIRSHIP_DOMAIN = '35.178.91.246'

describe('SOAP app', () => {
  it('can login using SOAP username and password', () => {
    const bundle = {
      // In production, these will be generated by Zapier and set automatically
      authData: {
        soap_username: process.env.SOAP_USERNAME,
        soap_password: process.env.SOAP_PASSWORD
      }
    };

    return appTester(App.authentication.test, bundle).then(
      response => {
        response.should.not.be.empty();
      }
    );
  });
});
